rules = [
  DisableSyntax
  OrganizeImports
  RedundantSyntax
  TypelevelAs
  TypelevelFs2SyncCompiler
  TypelevelHttp4sLiteralsSyntax
  TypelevelIORandomUUID
  TypelevelMapSequence
  TypelevelUnusedIO
  TypelevelUnusedShowInterpolator
]

DisableSyntax.noFinalize = true
DisableSyntax.noReturns = true
DisableSyntax.noXml = true

OrganizeImports.groups = [
  "re:javax?\\."
  "scala."
  "cats."
  "*"
  "io.github.biochimia."
]
